//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommerceDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public int ItemsQunatity { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ItemsId { get; set; }
        public string CustomerName { get; set; }
        public bool isDisable { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
