//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommerceDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ItemId { get; set; }
        public decimal PricePerUnit { get; set; }
        public string OrderedBy { get; set; }
        public int ItemsQuantity { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
